# 310-StudyInfoCTGov.rq Study information from remote Knowledge Graph


PREFIX eg: <http://example.org/LDWorkshop#>

SELECT ?study ?nctid ?p ?o

WHERE{
  ?study ct:nct-id ?nctid .

  SERVICE <http://bio2rdf.org/sparql>
  {
    ?nctid ?p ?o  .
  }
}
