# 510-PoolAllStudies.rq  - Pool all Studies. 
#   Script created 2019-11-04 12:06:38 by CreateSPARQLForPooling.R 
#       based on list of servers in ClassInfo.xlsx
INSERT {?s ?p ?o}
WHERE
{
    # Graph 1
    {
        SERVICE <http://18.236.210.166:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 2
    {
        SERVICE <http://18.237.119.21:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 3
    {
        SERVICE <http://18.237.137.64:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 4
    {
        SERVICE <http://18.237.225.108:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 5
    {
        SERVICE <http://18.237.43.88:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 6
    {
        SERVICE <http://18.237.62.27:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 7
    {
        SERVICE <http://34.211.58.197:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 8
    {
        SERVICE <http://34.212.172.44:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 9
    {
        SERVICE <http://34.213.10.227:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 10
    {
        SERVICE <http://34.219.147.244:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 11
    {
        SERVICE <http://34.221.63.174:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 12
    {
        SERVICE <http://35.162.217.55:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 13
    {
        SERVICE <http://35.167.252.62:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 14
    {
        SERVICE <http://52.25.233.140:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 15
    {
        SERVICE <http://52.43.135.225:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 16
    {
        SERVICE <http://54.148.147.180:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 17
    {
        SERVICE <http://54.184.139.125:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 18
    {
        SERVICE <http://54.190.11.144:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 19
    {
        SERVICE <http://54.200.183.88:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 20
    {
        SERVICE <http://54.200.43.255:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 21
    {
        SERVICE <http://54.202.54.138:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 22
    {
        SERVICE <http://54.245.52.99:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
}
