# 420-StudiesByPhase.rq   List studies by Phase
#  Execute on the Pooled Database

PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

SELECT ?phase ?study
WHERE
{
   ?study ncit:phase ?phase
} ORDER BY ?phase ?study