# 535-AllStudiesCountPeople.rq  Count all Persons involved all studies
#  (not just patients who participateIn a study)
# Execute on the Pooled Database
# Reasoner must be ON

PREFIX schema: <http://schema.org/>


SELECT  (COUNT(?person) as ?numAllPersons)
WHERE{
  ?person a schema:Person.
}
