# 330-NameHumanStudySubject.rq  Names of HumanStudySubjects in Study
#   Reasoner must be ON.

SELECT ?person_name
WHERE {
    ?person a eg:HumanStudySubject;
            schema:givenName   ?person_name .
}
