# 410-PoolAllStudies.rq  - Pool all Drug1 Studies. 
#   Script created 2018-02-20 12:26:47 by CreatePoolScript.R 
#       based on list of servers in ClassInfo.xlsx
INSERT {?s ?p ?o}
WHERE
{
    # Graph 1
    {
        SERVICE <http://52.14.114.74:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
    UNION
    # Graph 2
    {
        SERVICE <http://18.218.251.17:5820/LDWStudy/query>
        {
            SELECT ?s ?p ?o
            WHERE { ?s ?p ?o .} 
        }
    }
}
