# 435-Drug1CountPeople.rq  Count all people involved in Drug1 studies
# Execute on the Pooled Database
# Reasoner must be ON

SELECT  (COUNT(?person) as ?numSubjects)
WHERE{
  ?person a schema:Person.
}
