# 450-Drug1PersonsAllStudies.rq  Count all people involved in Drug1 studies
# Execute on the Pooled Database

SELECT  ?person ?person_name ?study ?person_type
WHERE{
    {
        ?person eg:participatesIn  ?study ;
                schema:givenName ?person_name .
        BIND ("HumanStudySubject" as ?person_type)
    }
    UNION
    {
        ?person eg:coordinatingInvestigator  ?study ;
                schema:givenName ?person_name .
      BIND ("Investigator" as ?person_type)
    }
} ORDER BY ?person ?person_name
