---
title: "EUConnect19 Workshop InfoSheets"
output:
  word_document: default
  pdf_document: default
fontsize: 14pt
---
# Handouts for Each Attendee
##  2019-11-12

\fontfamily{cmr}
\fontsize{12}{22}
\selectfont

\newpage


```{r echo=FALSE, results="asis", warning=FALSE}
# results=asis: needed for the page breaking
# Read the source file
library(knitr)
library(rmarkdown)
library(readxl)

servers <- as.data.frame(read_excel("C:/_gitHub/LinkedDataWorkshop/EUConnect19/data/admin/CourseInfo.xlsx", sheet = "Servers", col_names=TRUE))

# servers <- servers[ order(servers[,4], servers[,3]), ]

## Loop
for (i in 1:nrow(servers)){
  if (!is.na(servers[i,"ip"]))
  {
    
    cat("\n\n")
    cat("\\pagebreak")
    cat("\n\n")
    cat("#**Info Sheet**\n")
    cat("\n\n")
    # cat("##Attendee", i, "   ", servers[i,3], " ",  servers[i,4], "\n")
    cat("##Attendee", i, "\n")
    cat("\n\n")
    cat("\n\n")
    cat("##Server Information  ")
    cat("\n\n")
    cat(paste0("Computer: **", servers[i,"ip"],"**\n"))
    cat("\n\n")
    cat("User name: **phuseldw** \n")
    cat("\n\n")
    cat("Password: **Amster11!** \n")

    cat("\n\n")
    
    cat("****")
    cat("\n\n")
    cat("\n\n")
    
    cat("##Values for Exercises\n")
    cat(paste0("Study:  **Study", i,"**\n"))
    cat("\n\n")

    cat(paste0("NCTID: **", servers[i,"NCTID"],"**\n"))
    cat("\n\n")
    
    cat(paste0("Treat Arm One: **TrtArm",i,"-1**\n"))
    cat("\n\n")
    cat(paste0("Treat Arm Two: **TrtArm",i,"-2**\n"))
    cat("\n\n")  
  
    cat(paste0("Person One: \t**Person",i,"1**\n"))
    cat("\n\n")  
    cat(paste0("Person Two: **Person",i,"2**\n"))
    cat("\n\n")  
    cat(paste0("Person Three: **Person",i,"3**\n"))
    cat("\n\n")
    cat("\n\n\\pagebreak\n")
  }
}