
# SERVICE:
# http://drugbank.bio2rdf.org/sparql


#------------- Information about a Clinical Trial -----------------------------
# CLINICAL TRIAL information based on NCTID number
#  ct:NCTnnnnnn links from study graph out to Clinical Trials graph

#--- a) Study Phase
PREFIX ct:     <http://bio2rdf.org/clinicaltrials:>
PREFIX ct-voc: <http://bio2rdf.org/clinicaltrials_vocabulary:>
SELECT ?phaseName
WHERE
{
  SERVICE <http://bio2rdf.org/sparql> # both work
  {
    # <http://bio2rdf.org/clinicaltrials:NCT00175890> <http://bio2rdf.org/clinicaltrials_vocabulary:phase> ?phaseIRI .
    ct:NCT02301286  ct-voc:phase ?phaseIRI .
    ?phaseIRI ?p ?phaseName .
    FILTER regex(str(?phaseName), "^Phase \\d$", "i")
  } 
}

#--- b) Study Title
PREFIX ct-voc: <http://bio2rdf.org/clinicaltrials_vocabulary:>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?studyTitle
WHERE
{
  SERVICE <http://bio2rdf.org/sparql> # both work
  {
    ct:NCT00175890 dcterms:title ?studyTitle .  
  }
}

#--- Federated query :  Title and Phase for your trial
#  To become an Exercise query
# ERROR IN DATA FROM EDITOR: CT PREFIX NOT CORRECT IN DATA
PREFIX dcterms <http://purl.org/dc/terms/>
PREFIX ct      <http://bio2rdf.org/clinicaltrials:>
PREFIX ct-voc  <http://bio2rdf.org/clinicaltrials_vocabulary:>

WHERE{
#  { # My local graph
    ?studyIRI  ct:nct-id  ?nctid .
    BIND(?nctid AS ?nctidIRI)
#  }
 # SERVICE <http://bio2rdf.org/sparql> 
 # { # Clinical Trials remote graph
 #   ?nctidIRI  dcterms:title ?studyTitle ;    
 #              ct-voc:phase ?phaseIRI .
 #   ?phaseIRI ?p ?phaseName .
 #   FILTER regex(str(?phaseName), "^Phase \\d$", "i")
 # }
}  # End of WHERE statement





##----------- Information about Aspirin ---------------


#------ DBPEDIA ---------------------------------------#
# SERVICE: https://dbpedia.org/sparql

PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
SELECT *
WHERE{
  ?s  rdf:type dbpedia-owl:Drug ;
      rdfs:label  ?label
  FILTER regex(?label, "Aspirin", "i")
                  
}LIMIT 200

#--- Abstract for Aspirin
# Get the abstract for Aspirin at DBPedia
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpedia:   <http://dbpedia.org/resource/>

SELECT ?abstract
WHERE{
  SERVICE <http://dbpedia.org/sparql>
  {
    dbpedia:Aspirin dbpedia-owl:abstract ?abstract
    FILTER (lang(?abstract) = "en")
  }
}
